### ISSUE TITLE
Implement routing for your React app

### ISSUE THREAD

**Issue by sarahchungwu** [sarahchungwu/FurEverFriend#1]
Create the react route for the project

This is the route

/ (HomePage)
/signup (SignupLogin)
/login (SignupLogin)
/profile (UserProfile)
/dogs/new (DogForm)
/dogs/:id (DogProfile)
/dogs/:id/matches (MatchList)
/messages (MessageList)
/messages/:id (MessageDetail)

**Comment by Upendra-Jaiswal** [comment]
please assign it to me

**Comment by sarahchungwu** [comment]
Hi, sorry about the misleading; this issue is only for me to fix.
